### PR TITLE
Update demo.html

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
made the image responsive

### CODE REVIEW

**Comment by engrravijain** [comment]
nice work using the bootstrap framework. it would be great if you could implement the same without bootstrap.

**Comment by Vaibhav1671998** [comment]
@engrravijain Yes it would be fine but if we have things available why would we need to make things complicated if we can make them easy

**Comment by Vaibhav1671998** [comment]
@engrravijain it won't affect the network load as we can optimize the website too but adding just an attribute .

**Comment by engrravijain** [comment]
`cosole.log("great go on");`

**Comment by Vaibhav1671998** [comment]
Thanks @engrravijain

**Pull request closed without merging**
